name: openml-tags-octis
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10.14
  - jupyter==1.0.0
  - python-dotenv=1.0.1
  - seaborn=0.13.2
  - pip:
      - bertopic==0.16.1
      - scipy==1.12.0
      - octis==1.13.1
      - top2vec==1.0.27
      - contextualized_topic_models==2.5.0