name: openml-tags
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - python==3.11.9
  - pip==24.0
  - matplotlib==3.8.4
  - scikit-learn==1.4.2
  - jupyter==1.0.0
  - spacy==3.7.3
  - nltk==3.8.1
  - numpy==1.26.4
  - pandas==2.2.2
  - seaborn==0.13.2
  - gensim==4.3.2
  - plotly==5.22.0
  - pyldavis==3.4.1
  - wordcloud==1.9.3
  - textstat==0.7.3
  - scrapy=2.1.1
  - datashader=0.16.1
  - bokeh=3.4.1
  - holoviews=1.18.3
  - python-dotenv=1.0.1
  - pip:
      - bertopic==0.16.1
      - openml==0.14.2
      - spacy-transformers==1.3.5
      - urlextract==1.9.0
      - octis==1.13.1
      - top2vec==1.0.34
      # make sure to install llama-cpp-python based on your own configuration
      # - llama-cpp-python==0.2.62