name: openml-tags
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.12.2
  - matplotlib==3.8.3
  - scikit-learn==1.4.1.post1
  - jupyter==1.0.0
  - bertopic==0.16.0
  - spacy==3.7.2
  - nltk==3.8.1
  - numpy==1.26.4
  - pandas==2.2.1
  - pip:
      - openml==0.14.2