name: openml-tags
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - python==3.11.8
  - pip==24.0
  - matplotlib==3.8.3
  - scikit-learn==1.4.1.post1
  - jupyter==1.0.0
  - bertopic==0.16.0
  - spacy==3.7.2
  - nltk==3.8.1
  - numpy==1.26.4
  - pandas==2.2.1
  - seaborn==0.13.2
  - gensim==4.3.2
  - plotly==5.20.0
  - pyldavis==3.4.1
  - wordcloud==1.9.3
  - textstat==0.7.3
  - pip:
      - openml==0.14.2
      - spacy-transformers==1.3.4
      - urlextract==1.9.0